name = "trotteropt"
version = "0.1.0"
defaultTargets = ["TrotterOpt"]

[leanOptions]
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.1"

[[lean_lib]]
name = "TrotterOpt"
